# -*- coding: utf-8 -*-
"""project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BR03WL6pS89nu85JCqyZlHkMxDyrGCdy
"""

list = [2,4,6,8,10]
square = [i**2 for i in list]
print('square of the numbers are:',square)
cube = [i**3 for i in list]
print('cube of the numbers are :',cube)













